id: P008076
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6602
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར་
  author: ''
  volumes:
    83f6a96359744140833954a3d91d6be4:
      image_group_id: I1KG1435
      title: ''
      volume_number: 1
      total_pages: 72
ebook_metadata:
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར་
  author: ''
  sku: P008076
  cover: cover.jpg
  layers:
  - pagination
