id: opecha:P008076
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6602
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར་
  volume:
    bc84e228a68a40528a17ce010f42f64b:
      image_group_id: I1KG1435
      title: Volume 1 of gting skyes dgon pa byang sprul sku'i 'khrungs rabs rnam
        thar
      volume_number: 1
      total_pages: 72
  author: ''
ebook_metadata:
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར་
  author: ''
  sku: P008076
  cover: cover.jpg
  layers:
  - pagination
