id: P008076
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:50.723437
source_metadata:
  id: bdr:W2CZ6602
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར་
  author: ''
  volumes:
    bc84e228a68a40528a17ce010f42f64b:
      image_group_id: I1KG1435
      title: Volume 1 of gting skyes dgon pa byang sprul sku'i 'khrungs rabs rnam
        thar
      volume_number: 1
      total_pages: 72
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
