id: IBD6CE7E9
legacy_id: P008076
ocr_import_info:
  bdrc_scan_id: W2CZ6602
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:49:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:12:32.343061+00:00'
last_modified: 2022-09-02 23:12:52.013266
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ6602
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ6602
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏིང་སྐྱེས་དགོན་པ་བྱང་སྤྲུལ་སྐུའི་འཁྲུངས་རབས་རྣམ་ཐར།
  author: མཐའ་གྲོལ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6521076487767881
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG1435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1435
      total_pages: 72
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1435.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.6521076487767881
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
